# Generated by Django 5.1.1 on 2024-09-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_alter_clientprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_staff', to='client.clientprofile')),
            ],
        ),
    ]
