# Generated by Django 5.1.1 on 2024-09-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_clientprofile_contact_and_more'),
        ('schedule', '0002_remove_availabletime_date_object_and_more'),
        ('services', '0002_remove_servicerelatedstaff_service_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_staff', to='client.clientprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientStaff',
        ),
    ]
