# Generated by Django 5.1.1 on 2024-09-19 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_alter_clientprofile_user'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('is_free', models.BooleanField(default=False)),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='client.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRelatedStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_related_service', to='services.clientservices')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_related_staff', to='staff.clientstaff')),
            ],
        ),
    ]
