# Generated by Django 5.1.1 on 2024-09-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_clientprofile_contact_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerelatedstaff',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicerelatedstaff',
            name='staff',
        ),
        migrations.CreateModel(
            name='ServiceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_client', to='client.clientprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_service', to='services.clientservices')),
            ],
        ),
    ]
