# Generated by Django 5.1.1 on 2024-09-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_servicerelatedstaff_service_and_more'),
        ('staff', '0002_staffprofile_delete_clientstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesummary',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_staff', to='staff.staffprofile'),
        ),
        migrations.DeleteModel(
            name='ServiceRelatedStaff',
        ),
    ]
