# Generated by Django 5.1.1 on 2024-09-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicesummary_staff_delete_servicerelatedstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservices',
            name='currency',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientservices',
            name='image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
