# Generated by Django 5.1.1 on 2024-09-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_servicesummary_client'),
        ('staff', '0002_staffprofile_delete_clientstaff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceSummary',
            new_name='ServiceRelatedStaff',
        ),
        migrations.AlterField(
            model_name='clientservices',
            name='currency',
            field=models.CharField(default='usd', max_length=100),
        ),
    ]
