# Generated by Django 5.1.1 on 2024-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_servicesummary_servicerelatedstaff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientservices',
            name='currency',
        ),
        migrations.AddField(
            model_name='clientservices',
            name='duration',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientservices',
            name='total_minutes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
