# Generated by Django 5.1.1 on 2024-09-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_clientprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='contact',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='connect_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='connect_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='domain',
            field=models.CharField(max_length=700, unique=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='unique_key',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
