# Generated by Django 5.1.1 on 2024-11-17 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_companyprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='connect_url',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='connect_id',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='staff_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='client.clientprofile'),
        ),
    ]
