# Generated by Django 5.1.1 on 2024-11-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_rename_connect_url_clientprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='password',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
