# Generated by Django 5.1.1 on 2024-12-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_clientprofile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_active',
        ),
    ]
