# Generated by Django 5.1.1 on 2024-12-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_clientprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='using_auth_service',
            field=models.BooleanField(default=False),
        ),
    ]
