# Generated by Django 5.1.1 on 2024-09-24 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_format', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='availabledates',
            name='available_date',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=200)),
                ('date_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_related_time', to='schedule.availabledates')),
            ],
        ),
    ]
