# Generated by Django 5.1.1 on 2024-09-25 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_timeformat_alter_availabledates_available_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabledates',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 6, 12, 21, 437701, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
