# Generated by Django 5.1.1 on 2024-09-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_availabledates_created_at_availabletime_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
