# Generated by Django 5.1.1 on 2024-09-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_availabledates_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabledates',
            name='day',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availabledates',
            name='year',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
