# Generated by Django 5.1.1 on 2024-10-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_companyprofile'),
        ('schedule', '0007_availabledates_day_availabledates_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeFormat',
        ),
        migrations.AlterField(
            model_name='availabledates',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_related_client', to='client.clientprofile'),
        ),
    ]
