# Generated by Django 5.1.1 on 2024-10-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_delete_timeformat_alter_availabledates_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabledates',
            name='month',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
