# Generated by Django 5.1.1 on 2024-10-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_availabledates_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='end_time',
        ),
    ]
