# Generated by Django 5.1.1 on 2024-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_remove_availabletime_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
