# Generated by Django 5.1.1 on 2024-10-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_availabletime_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='hold_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
