# Generated by Django 5.1.1 on 2024-10-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_availabletime_hold_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='on_hold_for',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
