# Generated by Django 5.1.1 on 2024-10-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_availabletime_on_hold_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='on_hold_for',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
