# Generated by Django 5.1.1 on 2024-10-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_availabletime_on_hold_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
