# Generated by Django 5.1.1 on 2024-10-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_availabletime_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
