# Generated by Django 5.1.1 on 2024-10-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_alter_availabletime_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='start_time',
        ),
    ]
