# Generated by Django 5.1.1 on 2024-10-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_remove_availabletime_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('shift_starts', models.TimeField()),
                ('shift_ends', models.TimeField()),
                ('break_time_starts', models.TimeField()),
                ('break_time_ends', models.TimeField()),
            ],
        ),
    ]
