# Generated by Django 5.1.1 on 2024-10-31 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_companyprofile'),
        ('schedule', '0018_staffschedule'),
        ('staff', '0002_staffprofile_delete_clientstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffschedule',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_related_client', to='client.clientprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_related_staff', to='staff.staffprofile'),
            preserve_default=False,
        ),
    ]
