# Generated by Django 5.1.1 on 2024-11-03 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_staffschedule_client_staffschedule_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='break_time_ends',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='break_time_starts',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OnHoldTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_hold_slots', to='schedule.staffschedule')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('schedule', 'start_time', 'end_time')},
            },
        ),
    ]
