# Generated by Django 5.1.1 on 2024-11-03 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_companyprofile'),
        ('schedule', '0020_alter_staffschedule_break_time_ends_and_more'),
        ('staff', '0002_staffprofile_delete_clientstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnHoldTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_schedule', models.DateField(blank=True, null=True)),
                ('time_slot', models.TimeField(blank=True, null=True)),
                ('on_hold_for', models.TextField(blank=True, null=True)),
                ('on_hold_time', models.TimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_time_related_client', to='client.clientprofile')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_time_related_staff', to='staff.staffprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='OnHoldTimeSlot',
        ),
    ]
