# Generated by Django 5.1.1 on 2024-11-07 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_companyprofile'),
        ('schedule', '0021_onholdtimeslots_delete_onholdtimeslot'),
        ('staff', '0002_staffprofile_delete_clientstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('created_at', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_time_related_client', to='client.clientprofile')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_time_related_staff', to='staff.staffprofile')),
            ],
        ),
    ]
