# Generated by Django 5.1.1 on 2024-11-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_remove_onholdtimeslots_on_hold_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onholdtimeslots',
            name='on_hold',
        ),
    ]
