# Generated by Django 5.1.1 on 2024-12-24 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0011_clientprofile_using_auth_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_service_client', to='client.clientprofile')),
            ],
        ),
    ]
