# Generated by Django 5.1.1 on 2024-10-16 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0011_availabletime_on_hold'),
        ('services', '0007_remove_clientservices_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('booked_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_date', to='schedule.availabledates')),
                ('booked_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_time', to='schedule.availabletime')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_service', to='services.clientservices')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_staff', to='services.servicerelatedstaff')),
            ],
        ),
    ]
