# Generated by Django 5.1.1 on 2024-11-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentBooking',
        ),
    ]
