# Generated by Django 5.1.1 on 2024-11-15 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
        ('services', '0007_remove_clientservices_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointmentbooking',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='appointment_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='end_start_time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='start_time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='total_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='selected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AppointmentRelatedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='booking.appointmentbooking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_related_service', to='services.clientservices')),
            ],
        ),
    ]
