# Generated by Django 5.1.1 on 2024-11-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_appointmentbooking_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='track_id',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
