# Generated by Django 5.1.1 on 2024-11-21 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_appointmentbooking_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
