# Generated by Django 5.1.1 on 2024-11-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_appointmentbooking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
