# Generated by Django 5.1.1 on 2024-11-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_appointmentbooking_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentbooking',
            old_name='end_start_time_slot',
            new_name='end_time_slot',
        ),
    ]
