# Generated by Django 5.1.1 on 2024-11-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_end_start_time_slot_appointmentbooking_end_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
