# Generated by Django 5.1.1 on 2024-11-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_appointmentbooking_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='user_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
