# Generated by Django 5.1.1 on 2024-11-15 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0005_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_credentials', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment_related_client', to='client.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StripePaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_secret_key', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payment_related_client', to='client.clientprofile')),
            ],
        ),
    ]
