# Generated by Django 5.1.1 on 2024-09-30 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0005_companyprofile'),
        ('staff', '0002_staffprofile_delete_clientstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_client_account', to='client.clientprofile')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_staff_account', to='staff.staffprofile')),
            ],
        ),
    ]
