# Generated by Django 5.1.1 on 2024-11-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_generaluseraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaluseraccount',
            name='otp',
        ),
    ]
