# Generated by Django 5.1.1 on 2024-12-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_generaluseraccount_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluseraccount',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
