# Generated by Django 5.1.1 on 2024-12-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_generaluseraccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
